logging:
  config: classpath:log4j2-boot-dev.xml
  level:
    com.onion.template.spring.boot.mybatis.mapper: debug

#Redis 哨兵配置
spring:
  redis:
    sentinel:                   #哨兵配置
      master: my-master         #Redis服务器名称
      nodes:                    #Redis哨兵地址
        - 192.168.2.11:6379
        - 192.168.2.12:6379
        - 192.168.2.13:6379
    database: 0                 #Redis 索引（0~15，默认为0）
    timeout: 1000ms               #Redis 连接的超时时间
    password: 123456            #Redis 密码，如果没有就默认不配置此参数
    lettuce:                    #使用 lettuce 连接池
      pool:
        max-active: 20          #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms            #连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0             #连接池中的最大空闲连接
        max-idle: 10            #连接池中的最小空闲连接

#Redis 集群配置
spring:
  redis:
    database: 0                  #Redis 索引（0~15，默认为0）
    timeout: 1000ms                #Redis 连接的超时时间
    password: 123456             #Redis 密码，如果没有就默认不配置此参数
    cluster:                     #Redis 集群配置
      max-redirects: 5           #Redis 命令执行时最多转发次数
      nodes:                     #Redis 集群地址
        - 192.168.2.11:6379
        - 192.168.2.12:6379
        - 192.168.2.13:6379
        - 192.168.2.11:6380
        - 192.168.2.12:6380
        - 192.168.2.13:6380
    lettuce:                     #使用 lettuce 连接池
      pool:
        max-active: 20           #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms             #连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0              #连接池中的最大空闲连接
        max-idle: 10             #连接池中的最小空闲连接