package com.example.demo.entity;

import java.io.Serializable;
import java.util.Date;

public class TCtMessage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CT_MESSAGE.ID
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CT_MESSAGE.TJLX
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    private String tjlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CT_MESSAGE.SQL
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    private String sql;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CT_MESSAGE.TJZ
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    private String tjz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CT_MESSAGE.DWDM
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    private String dwdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CT_MESSAGE.BGSJ
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    private Date bgsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CT_MESSAGE.KBNAME
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    private String kbname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CT_MESSAGE.MODULEMS
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    private String modulems;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_CT_MESSAGE
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CT_MESSAGE.ID
     *
     * @return the value of T_CT_MESSAGE.ID
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CT_MESSAGE.ID
     *
     * @param id the value for T_CT_MESSAGE.ID
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CT_MESSAGE.TJLX
     *
     * @return the value of T_CT_MESSAGE.TJLX
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    public String getTjlx() {
        return tjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CT_MESSAGE.TJLX
     *
     * @param tjlx the value for T_CT_MESSAGE.TJLX
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    public void setTjlx(String tjlx) {
        this.tjlx = tjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CT_MESSAGE.SQL
     *
     * @return the value of T_CT_MESSAGE.SQL
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    public String getSql() {
        return sql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CT_MESSAGE.SQL
     *
     * @param sql the value for T_CT_MESSAGE.SQL
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    public void setSql(String sql) {
        this.sql = sql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CT_MESSAGE.TJZ
     *
     * @return the value of T_CT_MESSAGE.TJZ
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    public String getTjz() {
        return tjz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CT_MESSAGE.TJZ
     *
     * @param tjz the value for T_CT_MESSAGE.TJZ
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    public void setTjz(String tjz) {
        this.tjz = tjz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CT_MESSAGE.DWDM
     *
     * @return the value of T_CT_MESSAGE.DWDM
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    public String getDwdm() {
        return dwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CT_MESSAGE.DWDM
     *
     * @param dwdm the value for T_CT_MESSAGE.DWDM
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    public void setDwdm(String dwdm) {
        this.dwdm = dwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CT_MESSAGE.BGSJ
     *
     * @return the value of T_CT_MESSAGE.BGSJ
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    public Date getBgsj() {
        return bgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CT_MESSAGE.BGSJ
     *
     * @param bgsj the value for T_CT_MESSAGE.BGSJ
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    public void setBgsj(Date bgsj) {
        this.bgsj = bgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CT_MESSAGE.KBNAME
     *
     * @return the value of T_CT_MESSAGE.KBNAME
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    public String getKbname() {
        return kbname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CT_MESSAGE.KBNAME
     *
     * @param kbname the value for T_CT_MESSAGE.KBNAME
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    public void setKbname(String kbname) {
        this.kbname = kbname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CT_MESSAGE.MODULEMS
     *
     * @return the value of T_CT_MESSAGE.MODULEMS
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    public String getModulems() {
        return modulems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CT_MESSAGE.MODULEMS
     *
     * @param modulems the value for T_CT_MESSAGE.MODULEMS
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    public void setModulems(String modulems) {
        this.modulems = modulems;
    }
}