package com.example.demo.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class TCtUserMenu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CT_USER_MENU.KB
     *
     * @mbg.generated Wed Mar 01 16:26:50 CST 2023
     */
    private BigDecimal kb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CT_USER_MENU.USERID
     *
     * @mbg.generated Wed Mar 01 16:26:50 CST 2023
     */
    private BigDecimal userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CT_USER_MENU.KBORDER
     *
     * @mbg.generated Wed Mar 01 16:26:50 CST 2023
     */
    private BigDecimal kborder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CT_USER_MENU.ISSHOW
     *
     * @mbg.generated Wed Mar 01 16:26:50 CST 2023
     */
    private String isshow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_CT_USER_MENU
     *
     * @mbg.generated Wed Mar 01 16:26:50 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CT_USER_MENU.KB
     *
     * @return the value of T_CT_USER_MENU.KB
     *
     * @mbg.generated Wed Mar 01 16:26:50 CST 2023
     */
    public BigDecimal getKb() {
        return kb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CT_USER_MENU.KB
     *
     * @param kb the value for T_CT_USER_MENU.KB
     *
     * @mbg.generated Wed Mar 01 16:26:50 CST 2023
     */
    public void setKb(BigDecimal kb) {
        this.kb = kb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CT_USER_MENU.USERID
     *
     * @return the value of T_CT_USER_MENU.USERID
     *
     * @mbg.generated Wed Mar 01 16:26:50 CST 2023
     */
    public BigDecimal getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CT_USER_MENU.USERID
     *
     * @param userid the value for T_CT_USER_MENU.USERID
     *
     * @mbg.generated Wed Mar 01 16:26:50 CST 2023
     */
    public void setUserid(BigDecimal userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CT_USER_MENU.KBORDER
     *
     * @return the value of T_CT_USER_MENU.KBORDER
     *
     * @mbg.generated Wed Mar 01 16:26:50 CST 2023
     */
    public BigDecimal getKborder() {
        return kborder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CT_USER_MENU.KBORDER
     *
     * @param kborder the value for T_CT_USER_MENU.KBORDER
     *
     * @mbg.generated Wed Mar 01 16:26:50 CST 2023
     */
    public void setKborder(BigDecimal kborder) {
        this.kborder = kborder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CT_USER_MENU.ISSHOW
     *
     * @return the value of T_CT_USER_MENU.ISSHOW
     *
     * @mbg.generated Wed Mar 01 16:26:50 CST 2023
     */
    public String getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CT_USER_MENU.ISSHOW
     *
     * @param isshow the value for T_CT_USER_MENU.ISSHOW
     *
     * @mbg.generated Wed Mar 01 16:26:50 CST 2023
     */
    public void setIsshow(String isshow) {
        this.isshow = isshow;
    }
}