package com.example.demo.mapper;

import com.example.demo.entity.TCtMessage;

public interface TCtMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CT_MESSAGE
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CT_MESSAGE
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    int insert(TCtMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CT_MESSAGE
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    int insertSelective(TCtMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CT_MESSAGE
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    TCtMessage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CT_MESSAGE
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    int updateByPrimaryKeySelective(TCtMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CT_MESSAGE
     *
     * @mbg.generated Mon Feb 13 11:01:04 CST 2023
     */
    int updateByPrimaryKey(TCtMessage record);
}