package com.example.demo.mapper;

import com.example.demo.entity.TCtUserMenu;

public interface TCtUserMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CT_USER_MENU
     *
     * @mbg.generated Wed Mar 01 16:26:50 CST 2023
     */
    int insert(TCtUserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CT_USER_MENU
     *
     * @mbg.generated Wed Mar 01 16:26:50 CST 2023
     */
    int insertSelective(TCtUserMenu record);
}